### ISSUE TITLE
Breaking changes in tib

### ISSUE THREAD

**Issue by lackdaz** [mdegans/tib#13]
I'm trying to run a new nx image. 

Fresh 20.04 install

Steps to reproduce:
```
sudo apt install qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager
sudo adduser $USER libvirt
sudo snap install multipass
sudo pip3 install . && tib nx -v 2 -m 16G --patches extras/patches/nano_4.4.3_l4t32.4.3_rbpv3_imx477_support.patch --menuconfig --chroot-scripts extras/scripts/sysprep.sh extras/scripts/install_deepstream.sh extras/scripts/fix_boot_permissions.sh
```

Error
```
subprocess.CalledProcessError: Command '('/snap/bin/multipass', 'transfer', '/usr/local/lib/python3.8/dist-packages/tib/install_deps.sh', 'tib:/tmp/scriptdir/install_deps.sh')' returned non-zero exit status 1.
```

This error is also present on my other remote desktop `shadow`, which last ran a successful build on 07 Dec. Rolling back commits did not help.

**Comment by mdegans** [comment]
Cause is #6 

`sudo pip install` seems to be the problem. To fix, just install in a dedicated venv. Reason this happens on Linux is because Multipass is a snap app, snap apps are sandboxed, and sandboxed apps can only access certain paths (not including `/usr/local/...`).

**Comment by mdegans** [comment]
Feel free to reopen if this doesn't fix it for you.
